type Ability {
    name: String!
    url: String!
}

type AbilityDetails {
    ability: Ability!
    isHidden: Boolean!
    slot: Int!
}

type Cry {
    latest: String!
    legacy: String!
}

type Form {
    name: String!
    url: String!
}

type Version {
    name: String!
    url: String!
}

type GameIndex {
    gameIndex: Int!
    version: Version!
}

type VersionGroupDetail {
    levelLearnedAt: Int!
    moveLearnMethod: Version!
    versionGroup: Version!
}

type Move {
    name: String!
    url: String!
}

type MoveDetails {
    move: Move!
    versionGroupDetails: [VersionGroupDetail!]!
}

type Sprite {
    backDefault: String
    backFemale: String
    backShiny: String
    backShinyFemale: String
    frontDefault: String
    frontFemale: String
    frontShiny: String
    frontShinyFemale: String
}

type OtherSprites {
    dreamWorld: Sprite!
    home: Sprite!
    officialArtwork: Sprite!
    showdown: Sprite!
}

type Stat {
    baseStat: Int!
    effort: Int!
    stat: Ability!
}

type Type {
    slot: Int!
    type: Ability!
}

type Species {
    name: String!
    url: String!
}

type Pokemon {
    abilities: [AbilityDetails!]!
    baseExperience: Int!
    cries: Cry!
    forms: [Form!]!
    gameIndices: [GameIndex!]!
    height: Int!
    heldItems: [String!]!  # Assuming it's a list of item names/strings
    id: Int!
    isDefault: Boolean!
    locationAreaEncounters: String!
    moves: [MoveDetails!]!
    name: String!
    order: Int!
    pastAbilities: [Ability!]! # If this is a list of past abilities
    pastTypes: [Type!]!          # If this is a list of past types
    species: Species!
    sprites: OtherSprites!
    stats: [Stat!]!
    types: [Type!]!
    weight: Int!
}

type Query {
    getPokemon(id: Int!): Pokemon
}
